apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gvm.fullname" . }}-gvmd-db
type: Opaque
data:
data:
  type: {{ print "postgresql" | b64enc | quote }}
  port: {{ print "5432" | b64enc | quote }}
  username: {{ (index .Values "gvmd-db").postgresqlUsername | b64enc | quote }}
  password: {{ (index .Values "gvmd-db").postgresqlPassword  | b64enc | quote }}
  postgresql-password: {{ (index .Values "gvmd-db").postgresqlPassword  | b64enc | quote }}
  database: {{ (index .Values "gvmd-db").postgresqlDatabase | b64enc | quote }}
